package videonow

//id INT(11) unsigned PRIMARY KEY NOT NULL,
//site_id INT(11) unsigned NOT NULL,
//created DATE NOT NULL,
//is_active TINYINT(1) unsigned DEFAULT '1' NOT NULL,
//is_test TINYINT(1) unsigned DEFAULT '0' NOT NULL,
//is_bad TINYINT(3) unsigned DEFAULT '0' NOT NULL,
//title VARCHAR(64) NOT NULL,
//json TEXT,
//lang TINYINT(1) unsigned NOT NULL,
//conf_preroll_video ENUM('', 'on') NOT NULL,
//conf_experiment ENUM('', 'on') NOT NULL,
//conf_preroll_video_timer ENUM('', 'on') NOT NULL,
//conf_preroll_video_skip ENUM('', 'on', 'adv_knows') NOT NULL,
//conf_preroll_video_npd INT(4) NOT NULL,
//conf_preroll_video_ownmax DECIMAL(1,1) unsigned DEFAULT '0.3' NOT NULL,
//conf_preroll_video_freq INT(4) DEFAULT '0' NOT NULL,
//conf_postroll_video ENUM('', 'on') DEFAULT 'on' NOT NULL,
//conf_postroll_video_timer ENUM('', 'on') DEFAULT 'on' NOT NULL,
//conf_postroll_video_skip ENUM('', 'on') DEFAULT 'on' NOT NULL,
//conf_postroll_video_npd INT(4) DEFAULT '0' NOT NULL,
//conf_postroll_video_ownmax DECIMAL(1,1) DEFAULT '0.1' NOT NULL,
//conf_postroll_video_freq INT(4) DEFAULT '1' NOT NULL,
//conf_pauseroll_video ENUM('', 'on') DEFAULT 'on' NOT NULL,
//conf_pauseroll_video_timer ENUM('', 'on') DEFAULT 'on' NOT NULL,
//conf_pauseroll_video_npd INT(4) DEFAULT '2' NOT NULL,
//conf_pauseroll_video_ownmax DECIMAL(1,1) DEFAULT '0.1' NOT NULL,
//conf_pauseroll_video_freq INT(4) DEFAULT '1' NOT NULL,
//conf_contentroll_video ENUM('', 'on') DEFAULT 'on' NOT NULL,
//conf_contentroll_video_timer ENUM('', 'on') DEFAULT 'on' NOT NULL,
//conf_contentroll_video_npd INT(4) DEFAULT '2' NOT NULL,
//conf_contentroll_video_ownmax DECIMAL(1,1) DEFAULT '0.1' NOT NULL,
//conf_contentroll_video_freq INT(4) DEFAULT '1' NOT NULL,
//conf_contentroll_video_afterplay TINYINT(4) NOT NULL,
//conf_contentroll_video_afterplay_color_bg CHAR(6) DEFAULT 'DBDBDB' NOT NULL,
//conf_contentroll_selector VARCHAR(255),
//conf_contentroll_selector_percent TINYINT(3),
//conf_contentroll_width_element VARCHAR(255),
//conf_contentroll_create_type ENUM('element', 'after', 'before') DEFAULT 'element' NOT NULL,
//conf_contentroll_parent_element VARCHAR(255),
//conf_contentroll_no_ad_callback VARCHAR(255) DEFAULT '' NOT NULL,
//conf_contentroll_dynamic VARCHAR(100) DEFAULT '' NOT NULL COMMENT 'Элемент для отслеживания изменений',
//conf_contentroll_load_type ENUM('now', 'scrollstart') COMMENT 'Загрузка модуля для contentroll: now-сразу, scrollstart-при начале скроллинга',
//conf_overlay_video ENUM('', 'on') NOT NULL,
//conf_overlay_video_first TINYINT(2) unsigned,
//conf_overlay_video_freq TINYINT(2) unsigned,
//conf_overlay_video_limit TINYINT(2) unsigned,
//conf_overlay_video_place ENUM('load', 'scroll', 'second_screen'),
//conf_video_type_including ENUM('direct', 'adfox', 'dfp') COMMENT 'Тип встраивания для overlay и contentroll: direct-прямое встраивание, AdFox, DFP',
//conf_overlay_timeout_type TINYINT(1) unsigned,
//conf_overlay_timeout INT(10) unsigned,
//conf_contentroll_video_afterplay_color_text CHAR(6) DEFAULT '242424' NOT NULL,
//conf_slideroll_video ENUM('', 'on') DEFAULT '' NOT NULL,
//conf_slideroll_selector_percent TINYINT(3),
//conf_slideroll_selector VARCHAR(255),
//conf_slideroll_lookup_element VARCHAR(100),
//conf_continuousroll_video ENUM('', 'on') DEFAULT '' NOT NULL,
//conf_continuousroll_selector VARCHAR(255),
//conf_continuousroll_min_dintance TINYINT(4),
//conf_continuousroll_min_segments TINYINT(4) DEFAULT '3' NOT NULL,
//conf_continuousroll_max_segments TINYINT(4) DEFAULT '-1' NOT NULL,
//conf_continuousroll_lookup_element VARCHAR(100),
//vpaid_type TINYINT(1) DEFAULT '0' NOT NULL,
//settings TEXT NOT NULL,
//cash_in FLOAT UNSIGNED NOT NULL,
//use_content ENUM('', 'on') NOT NULL,
//partner_plan_id INT(10) unsigned NOT NULL,
//category_id INT(11),
//connection_type_id TINYINT(4) NOT NULL,
//device_id TINYINT(4) NOT NULL COMMENT 'Платформа (веб, смарт-тв, мобильники)',
//container_type_id TINYINT(4) NOT NULL COMMENT 'Где показывается реклама - в плеере, в тексте сайта, или ещё где',
//is_words_prohibited ENUM('', 'on') NOT NULL,
//words_prohibited TEXT NOT NULL,
//selector_words_prohibited VARCHAR(100) DEFAULT '' NOT NULL,
//comment TEXT NOT NULL,
//admin_sorting INT(11) DEFAULT '0' NOT NULL,
//preroll_id INT(11) COMMENT 'id псевдопреролла',
//vn_after_play BLOB COMMENT 'vnAfterPlay код',
//target_url_type ENUM('target', 'ban'),
//target_list_url TEXT NOT NULL,
//js_url_source ENUM('production', 'stage', 'custom') DEFAULT 'production' NOT NULL,
//new_js_module TINYINT(1) DEFAULT '0' NOT NULL,
//conf_slideroll_skip_type TINYINT(4),
//conf_slideroll_no_skip_time INT(11)

type Profile struct {
	Id uint64					`json:"id",bson:"id"` //id INT(11) unsigned PRIMARY KEY NOT NULL,
	Title string					`json:"title",bson:"title"` //title VARCHAR(64) NOT NULL,
	Site Site					`json:"site",bson:"site"`//site_id INT(11) unsigned NOT NULL,
	IsActive bool					`json:"is_active",bson:"is_active"`//is_active TINYINT(1) unsigned DEFAULT '1' NOT NULL,
	IsTest bool					`json:"is_test",bson:"is_test"`//is_test TINYINT(1) unsigned DEFAULT '0' NOT NULL,
	IsBad bool					`json:"is_bad",bson:"is_bad"`//is_bad TINYINT(3) unsigned DEFAULT '0' NOT NULL,
	Category Category				`json:"category",bson:"category"`//category_id INT(11),
	Financial []ProfileFinancial			`json:"financial",bson:"financial"`
	FinancialContent []ProfileFinancialContent	`json:"financial_content",bson:"financial_content"`
	//ContainerTypeId		//container_type_id TINYINT(4) NOT NULL COMMENT 'Где показывается реклама - в плеере, в тексте сайта, или ещё где',
	//Device	Device		//device_id TINYINT(4) NOT NULL COMMENT 'Платформа (веб, смарт-тв, мобильники)',
	//VpaidType		//vpaid_type TINYINT(1) DEFAULT '0' NOT NULL,
	CashIn float64					`json:"cash_in",bson:"cash_in"`//cash_in FLOAT UNSIGNED NOT NULL,
	UseContent bool					`json:"use_content",bson:"use_content"`//ENUM('', 'on') NOT NULL,
	PartnerPlanId uint64				`json:"partner_plan_id",bson:"partner_plan_id"`//INT(10) unsigned NOT NULL,

}